# ============================================================
# 01_build_si.R
# Builds the Supporting Information document entirely from pipeline outputs:
#   outputs/manuscript/Supporting_Information.docx
#   outputs/manuscript/si_items.csv   (item number, title, source file) for cross-referencing
# Every table is formatted from a CSV written by the analysis scripts and every figure is a
# file written by them; nothing is typed by hand except captions and the decay-class key.
# Run after the full pipeline (scripts/run_pipeline.sh calls it last).
# ============================================================
suppressPackageStartupMessages({ library(officer); library(flextable); library(dplyr); library(tidyr) })
OUT <- "outputs/manuscript"; dir.create(OUT, showWarnings = FALSE, recursive = TRUE)
T_ <- "outputs/tables"; MC <- file.path(T_, "model_checks"); MN <- file.path(T_, "manuscript"); FIG <- "outputs/figures"
rd <- function(f) read.csv(f, check.names = FALSE, stringsAsFactors = FALSE)
f2 <- function(x, d = 2) formatC(x, format = "f", digits = d)
fp <- function(p) ifelse(is.na(p), "", ifelse(p < 0.001, "<0.001", formatC(p, format = "f", digits = 3)))
star <- function(p) ifelse(is.na(p), "", ifelse(p < 0.001, "***", ifelse(p < 0.01, "**", ifelse(p < 0.05, "*", ""))))
sp_full <- c(bg = "N. sylvatica", rm = "A. rubrum", hem = "T. canadensis", ro = "Q. rubra")
term_lab <- function(t) { t <- gsub("TS_Ha[12]_raw_(\\d+)h", "Temperature (\\1 h)", t); t <- gsub("bvs_wtd_cm_raw_(\\d+)h", "Water table (\\1 h)", t)
  t <- gsub("NEON_SWC_shallow_raw_(\\d+)h", "Soil water (\\1 h)", t); t <- gsub("species", "", t); t <- gsub(":", " × ", t); t }

doc <- read_docx()
items <- list(); tab_n <- 0; fig_n <- 0
# Stable keys -> SI numbers (the manuscript cites items by key; see manuscript_work/edit_manuscript.py)
TAB_KEYS <- c("decay_key", "tomo_trees", "decay_corr", "decay_robust", "deadband", "wet_comp", "slopes",
              "upland", "coefs", "diagnostics", "window_null", "transform")
FIG_KEYS <- c("site_map", "drivers", "trajectories", "pred_by_site", "generalists", "spec_mean",
              "cv_obs_wetland", "cv_obs_upland", "decay_metrics")
TXT_KEYS <- c("flux", "models")
lab <- c(setNames(paste0("S", seq_along(TAB_KEYS)), paste0("T:", TAB_KEYS)),
         setNames(paste0("S", seq_along(FIG_KEYS)), paste0("F:", FIG_KEYS)),
         setNames(paste0("S", seq_along(TXT_KEYS)), paste0("X:", TXT_KEYS)))
fill <- function(x) { for (k in names(lab)) x <- gsub(paste0("{", k, "}"), lab[[k]], x, fixed = TRUE); x }
ft_style <- function(ft) ft %>% theme_booktabs() %>% fontsize(size = 8, part = "all") %>% font(fontname = "Arial", part = "all") %>%
  autofit() %>% fit_to_width(6.5)
add_table <- function(df, title, note, src, key) {
  tab_n <<- tab_n + 1; stopifnot(TAB_KEYS[tab_n] == key); note <- fill(note)
  doc <<- doc %>% body_add_par(sprintf("Table S%d. %s", tab_n, title), style = "Normal") %>%
    body_add_flextable(ft_style(flextable(df))) %>% body_add_par(note, style = "Normal") %>% body_add_par("", style = "Normal")
  items[[length(items) + 1]] <<- data.frame(key = paste0("T:", key), item = sprintf("Table S%d", tab_n), title = title, source = src)
}
add_figure <- function(path, title, caption, key, w = 6.5, h = NULL) {
  if (!file.exists(path)) stop("missing figure: ", path)
  fig_n <<- fig_n + 1; stopifnot(FIG_KEYS[fig_n] == key); caption <- fill(caption)
  if (is.null(h)) { dims <- dim(png::readPNG(path, native = TRUE)); h <- w * dims[1] / dims[2] }
  if (h > 8.5) { w <- w * 8.5 / h; h <- 8.5 }
  doc <<- doc %>% body_add_img(path, width = w, height = h) %>%
    body_add_par(sprintf("Figure S%d. %s %s", fig_n, title, caption), style = "Normal") %>% body_add_break()
  items[[length(items) + 1]] <<- data.frame(key = paste0("F:", key), item = sprintf("Figure S%d", fig_n), title = title, source = path)
}

doc <- doc %>% body_add_par("Supporting Information", style = "heading 1") %>%
  body_add_par("Contrasting controls on tree methane emissions in upland and wetland forests", style = "Normal") %>%
  body_add_par(sprintf("Generated by scripts/05_manuscript/01_build_si.R on %s from the pipeline outputs.", Sys.Date()), style = "Normal") %>%
  body_add_break()

# ---------------- Methods texts ----------------
md <- readLines("scripts/05_manuscript/si_methods.md", encoding = "UTF-8")
for (ln in md) {
  if (grepl("^## ", ln)) {
    k <- sub("^## (\\w+) \\|.*", "\\1", ln); ttl <- trimws(sub("^## \\w+ \\|", "", ln))
    doc <- doc %>% body_add_par(ttl, style = "heading 2")
    items[[length(items) + 1]] <- data.frame(key = paste0("X:", k), item = sub("\\..*", "", ttl), title = ttl, source = "scripts/05_manuscript/si_methods.md")
  } else if (nzchar(trimws(ln))) doc <- doc %>% body_add_par(fill(ln), style = "Normal")
}
doc <- doc %>% body_add_break()

# ---------------- Tables ----------------
# Main-text Table 1 (study trees and stand context) from 02_analysis/13_stand_context.R
fx <- rd("data/processed/flux_with_quality_flags.csv")
st <- rd(file.path(T_, "stand_context.csv")); tot <- rd(file.path(T_, "stand_totals.csv"))
t1 <- st %>% transmute(Site = ifelse(site == "Wetland", "Wetland (BGS)", "Upland (EMS)"), Species = species, n = n_trees,
                       `DBH, mean (range), cm` = sprintf("%.1f (%.1f–%.1f)", dbh_mean_cm, dbh_min_cm, dbh_max_cm),
                       `Stand DBH quartiles, cm` = sprintf("%d / %d / %d", stand_dbh_p25_cm, stand_dbh_p50_cm, stand_dbh_p75_cm),
                       `Live basal area, % (near study trees)` = ifelse(is.na(pct_live_basal_area_near_trees), as.character(pct_live_basal_area),
                                                                     sprintf("%d (%d)", pct_live_basal_area, pct_live_basal_area_near_trees)))
write.csv(t1, file.path(OUT, "table1.csv"), row.names = FALSE, fileEncoding = "UTF-8")
write.csv(tot, file.path(OUT, "table1_totals.csv"), row.names = FALSE)

# decay classification key (merged with class counts)
key <- data.frame(Class = c("I (No decay)", "II (Incipient)", "III (Active)", "IV (Cavity)"),
  `ERT moisture anomaly` = c("No", "Yes", "Yes", "No"), `SoT structural loss > 1%` = c("No", "No", "Yes", "Yes"),
  Interpretation = c("Sound wood", "Moisture anomaly without structural loss (wetwood or early decay)",
                     "Moisture anomaly with structural loss", "Structural loss without a moisture anomaly (hollow or desiccated decay)"),
  check.names = FALSE)
cls <- rd("data/processed/tomography_classes.csv") %>% filter(!is.na(decay_class)) %>% count(decay_class)
key$`Trees (n)` <- cls$n[match(sub(" .*", "", key$Class), sub(":.*", "", cls$decay_class))]
add_table(key, "Decay classification (from the companion tomography study).",
  "Moisture anomaly: species-normalized ERT PC1 above the study-set mean. Structural loss: > 1% of the SoT cross-section in non-brown (low-velocity) classes. Counts are the 57 trees with both scans.",
  "scripts/01_import/11_tomography_classes.R", "decay_key")

# S3 per-tree tomography metrics
ert <- rd("data/input/tomography_results_compiled.csv"); names(ert)[1] <- sub("^﻿", "", names(ert)[1])
tc <- rd("data/processed/tomography_classes.csv")
tm <- fx %>% group_by(Tree) %>% summarise(`Mean CH₄ flux` = f2(mean(CH4_flux_nmolpm2ps, na.rm = TRUE), 3), .groups = "drop")
t3 <- tc %>% left_join(ert %>% select(tree, ert_mean, ert_cv), by = "tree") %>% left_join(tm, by = c(tree = "Tree")) %>%
  transmute(Site = site, Species = sp_full[species], Tree = tree, `ERT mean (Ω m)` = f2(ert_mean, 0), `ERT CV` = f2(ert_cv, 3),
            `ERT PC1` = f2(ert_pc1, 2), `SoT loss (%)` = f2(sot_structural_loss, 1), Class = sub(":.*", "", decay_class), `Mean CH₄ flux`) %>%
  arrange(desc(Site), Species, Tree)
add_table(t3, "Tomography metrics, decay class and mean CH₄ flux (nmol m⁻² s⁻¹) of each study tree.",
  "ERT PC1: first principal component of eight ERT metrics, each standardized within species (higher = wetter, more heterogeneous). Trees without a complete SoT scan have no class.",
  "data/processed/tomography_classes.csv; data/input/tomography_results_compiled.csv", "tomo_trees")

# S4 wood-condition metric correlations
s4 <- rd(file.path(T_, "SI_decay_metric_correlations.csv"))
add_table(s4, "Correlations of tree-mean CH₄ flux with four wood-condition metrics.",
  "Pearson r (p) for each species × site (10 trees) and each site pooled (30 trees); the species-adjusted rows give the standardized coefficient β (p, likelihood-ratio test) of the metric in a mixed model of all measurements with species as a fixed effect and tree as a random effect. * p < 0.05.",
  "scripts/02_analysis/09_decay_definitions.R", "decay_corr")

# S5 decay robustness
rb <- rd(file.path(T_, "decay_robustness_correlations.csv")) %>% filter(SPECIES %in% c("ro", "bg"), metric %in% c("ert_cv", "ert_pc1")) %>%
  mutate(Species = sp_full[SPECIES], Metric = ifelse(metric == "ert_cv", "ERT CV", "ERT PC1"),
         Fluxes = recode(version, legacy = "Original fits", current = "Recalculated (analysis)", goflux_db00 = "Deadband 0 s",
                         goflux_db10 = "Deadband 10 s", goflux_db20 = "Deadband 20 s", goflux_db30 = "Deadband 30 s", goflux_db45 = "Deadband 45 s"),
         Summary = recode(summary, mean = "Mean", median = "Median", mean_detected = "Mean, detected only", mean_growing_season = "Mean, May–Oct"),
         cell = sprintf("%.2f (%s); LOO %.2f to %.2f", r, fp(p), loo_min, loo_max)) %>%
  filter(Summary == "Mean" | Fluxes == "Recalculated (analysis)") %>%
  select(Species, Metric, Fluxes, Summary, cell) %>% pivot_wider(names_from = Metric, values_from = cell) %>% arrange(Species, Summary, Fluxes)
add_table(rb, "Robustness of the specialist wood-condition–flux correlations.",
  "Pearson r (p) of tree-mean (or median) flux with ERT CV and ERT PC1, and the range of r when each tree is omitted in turn (LOO), for the original linear fits, the recalculated fluxes with deadbands of 0–45 s, and alternative tree summaries.",
  "scripts/02_analysis/10_decay_robustness.R", "decay_robust")

# S6 deadband sensitivity
db <- rd(file.path(T_, "deadband_sensitivity_summary.csv")) %>%
  transmute(Analyzer = sub("LGR/UGGA", "MGGA", inst), Site = location, `Deadband (s)` = deadband_s, n,
            `Mean flux` = f2(mean_flux, 3), `Median flux` = f2(median_flux, 3), `Median ratio to 0 s` = f2(median_ratio_to_db0, 2),
            `Change > 25% (%)` = f2(pct_change_gt25, 1), `Sign changes` = sign_changes)
add_table(db, "Sensitivity of fluxes (nmol m⁻² s⁻¹) to the deadband discarded after chamber closure.",
  "Each closure refitted with 0–45 s discarded after closure; the analysis uses 20 s.", "scripts/01_import/13_deadband_sensitivity.R", "deadband")

# S7 wetland model comparison (shared observations)
wc <- rd(file.path(MC, "wetland_model_comparison_common_rows.csv")) %>%
  transmute(Model = model, n, `Parameters (fixed)` = k_fixed, `Marginal R² (%)` = f2(100 * R2_marginal, 1), AIC = f2(AIC, 1), `ΔAIC` = f2(dAIC, 1), BIC = f2(BIC, 1), `ΔBIC` = f2(dBIC, 1))
add_table(wc, "Wetland model comparison on the observations with every driver available.",
  "All models include random intercepts for tree and sampling date. The extended model adds the predictors selected in 01_bgs_model.R (each improved the core model by likelihood-ratio test and ΔAIC < −2); the core model was retained because the extended model has a higher BIC.",
  file.path(MC, "wetland_model_comparison_common_rows.csv"), "wet_comp")

# S8 species-specific slopes: wetland core (all obs), wetland extended (shared obs), upland Model B
sl_core <- rd(file.path(MN, "species_slopes_wetland_core.csv")) %>% mutate(model = "Wetland core (all observations)")
sl_ext <- rd(file.path(MC, "wetland_species_slopes_core_vs_extended.csv")) %>% filter(model == "extended (shared rows)") %>%
  mutate(species = sp_full[species], model = "Wetland extended (shared observations)")
sl_upB <- rd(file.path(MN, "species_slopes_upland_B.csv")) %>% mutate(model = "Upland Model B")
sl <- bind_rows(sl_core, sl_ext, sl_upB) %>%
  mutate(effect = ifelse(grepl(":", term), "Temperature × water table", ifelse(grepl("^TS", term), "Temperature", "Water table")),
         cell = sprintf("%.3f ± %.3f%s", estimate, se, star(p))) %>%
  select(Model = model, Species = species, effect, cell) %>% pivot_wider(names_from = effect, values_from = cell)
add_table(sl, "Species-specific standardized effects of temperature and water table (asinh scale).",
  "Species-specific slope = reference coefficient + species interaction, ± SE; Satterthwaite t-tests. * p < 0.05; ** p < 0.01; *** p < 0.001. Upland Model B uses the wetland predictors and windows for direct comparison.",
  "species_slopes_*.csv; wetland_species_slopes_core_vs_extended.csv", "slopes")

# S9 upland models
ve <- rd(file.path(MC, "variance_explained.csv")); ab <- rd(file.path(MC, "upland_A_vs_B_common_rows.csv"))
sp_only <- ve %>% filter(model == "species only") %>% select(model_set, r2_sp = R2_marginal)
up <- ve %>% filter(model_set %in% c("upland_A", "upland_B"), model == "final") %>% left_join(sp_only, by = "model_set") %>%
  transmute(Model = ifelse(model_set == "upland_A", "A (upland drivers, 1 h)", "B (wetland drivers and windows)"), n,
            `Marginal R² (%)` = f2(100 * R2_marginal, 1), `Species only (%)` = f2(100 * r2_sp, 1),
            `AIC, all observations` = f2(AIC, 1)) %>%
  mutate(`AIC, shared observations` = f2(ab$AIC, 1), `n shared` = ab$n)
add_table(up, "Upland models.", "AIC is comparable only on the shared observations.", file.path(MC, "variance_explained.csv"), "upland")

# S10 all coefficients
co <- bind_rows(lapply(c(wetland_core = "Wetland core", upland_A = "Upland A", upland_B = "Upland B"), function(x) x) %>%
  { mapply(function(k, lab) rd(file.path(MN, paste0("coefficients_", k, ".csv"))) %>% mutate(Model = lab), names(.), ., SIMPLIFY = FALSE) }) %>%
  transmute(Model, Term = term_lab(term), Estimate = f2(estimate, 3), SE = f2(se, 3), df = f2(df, 1), t = f2(t, 2), p = fp(p))
add_table(co, "Fixed-effect coefficients of the final models (asinh scale; standardized predictors).",
  "Reference species: N. sylvatica (wetland) and A. rubrum (upland). Satterthwaite degrees of freedom.", "outputs/tables/manuscript/coefficients_*.csv", "coefs")

# S11 diagnostics: variance explained, out-of-sample, accuracy and bias
oos <- rd(file.path(MC, "out_of_sample.csv")); acc <- rd(file.path(MC, "accuracy_bias.csv")); ts <- rd(file.path(MC, "temperature_vs_season.csv"))
lab_ms <- c(wetland = "Wetland core", upland_A = "Upland A", upland_B = "Upland B")
dg <- ve %>% filter(model %in% c("species only", "final")) %>% select(model_set, model, R2_marginal) %>%
  pivot_wider(names_from = model, values_from = R2_marginal) %>%
  left_join(oos, by = "model_set") %>% left_join(acc %>% filter(prediction == "leave-one-date-out"), by = "model_set") %>%
  left_join(ts %>% select(model_set, R2_temperature_by_season, departure_LRT_p), by = "model_set") %>%
  transmute(Model = lab_ms[model_set], `R² species only` = f2(`species only`, 3), `R² final` = f2(final, 3),
            `Predictive R², leave-one-date-out (species only)` = sprintf("%.2f (%.2f)", lodo_R2_final, lodo_R2_species),
            `Predictive R², leave-one-tree-out (species only)` = sprintf("%.2f (%.2f)", loto_R2_final, loto_R2_species),
            `RMSE / bias, asinh scale` = sprintf("%.2f / %+.3f", rmse_asinh, bias_asinh),
            `MAE, nmol m⁻² s⁻¹` = f2(mae_nmol, 2),
            `Mean predicted / observed (smeared)` = sprintf("%.2f (%.2f)", ratio_mean_pred_obs, ratio_mean_smeared_obs),
            `2025 predicted from 2023–24, within range (species only)` = sprintf("%.2f (%.2f)", split2025_R2_in_range, split2025_R2_species_in_range),
            `Temperature explained by season (%)` = f2(100 * R2_temperature_by_season, 0),
            `p, temperature departure from season` = fp(departure_LRT_p))
dg <- as.data.frame(t(dg[, -1])) %>% setNames(dg$Model) %>% tibble::rownames_to_column("Diagnostic")
add_table(dg, "Model diagnostics.",
  "Marginal R² (Nakagawa). Out-of-sample predictions include the tree random effect (dates omitted) or fixed effects only (trees omitted). Bias = mean(predicted − observed). The back-transformed mean ratio shows the underestimate of mean flux from sinh(predicted mean); the smeared ratio applies Duan's (1983) correction. 2025 test restricted to observations within the 2023–24 predictor range.",
  "outputs/tables/model_checks/", "diagnostics")

# S12 window screening null
wp <- rd(file.path(MC, "window_permutation.csv")) %>%
  transmute(Model = lab_ms[model_set], Variable = variable, `Best window (h)` = best_window_h, `max |r|` = f2(max_abs_r, 2),
            `Windows within 0.02 of best (h)` = `windows_within_0.02_h`, `Null 95th percentile` = f2(null_95, 2), `Permutation p` = fp(p_perm))
add_table(wp, "Window screening against a date-permutation null.",
  "For each model driver, the maximum |r| over all windows (3 h–14 d) compared with 500 permutations in which environmental records were reassigned among sampling dates and the window search repeated.",
  file.path(MC, "window_permutation.csv"), "window_null")

# S13 transformation sensitivity
tr <- rd(file.path(MC, "transformation_sensitivity.csv")) %>% filter(term != "(Intercept)") %>%
  mutate(cell = sprintf("%.2f%s", t, star(p))) %>% select(Model = model_set, Term = term, transform, cell) %>%
  pivot_wider(names_from = transform, values_from = cell) %>% mutate(Model = lab_ms[Model], Term = term_lab(Term))
add_table(tr, "Sensitivity of the model terms to the flux transformation (t statistics).",
  "* p < 0.05; ** p < 0.01; *** p < 0.001.", file.path(MC, "transformation_sensitivity.csv"), "transform")

doc <- doc %>% body_add_break()

# ---------------- Figures ----------------
add_figure(file.path(FIG, "site_map.png"), "Study sites.",
  "(a) Location of Harvard Forest. (b) Prospect Hill tract: elevation, Black Gum Swamp outline, the study trees at the wetland (Black Gum Swamp) and upland (EMS) sites, the 40 points of the 2025 prism survey of the swamp (crosses), and the EMS, hemlock and NEON flux towers. (c, d) Study trees by species at each site. Tree positions from field GPS surveys.", "site_map")
add_figure(file.path(FIG, "si_driver_timeseries.png"), "Environmental drivers over the study period.",
  "Daily means (precipitation: daily totals) from June 2023 to October 2025; vertical lines mark wetland (solid) and upland (dashed) sampling dates. Note the summer 2025 drought (falling water table and soil water content).", "drivers")
add_figure(file.path(FIG, "repeatability", "fig_trajectories_blups.png"), "Tree flux trajectories and tree random effects.",
  "Left: flux of each tree over time (asinh scale). Right: tree random effects (BLUPs) with 95% intervals; red where the interval excludes zero.", "trajectories")
add_figure(file.path(FIG, "interaction_by_site_limited_free.png"), "Model predictions by site and species.",
  "Predicted CH₄ flux across the observed temperature range at different water-table percentiles, for each species, from the wetland core model and upland Model B.", "pred_by_site")
add_figure(file.path(FIG, "tomography", "tomography_generalists.png"), "Internal wood condition and CH₄ flux in the generalist species.",
  "As Figure 5, for A. rubrum and T. canadensis at both sites.", "generalists")
add_figure(file.path(FIG, "tomography", "tomography_specialists_SI_mean.png"), "Specialist species ordered by mean ERT resistivity.",
  "As Figure 5a, c, with trees ordered by mean resistivity instead of ERT CV.", "spec_mean")
for (s in c("wetland", "upland")) add_figure(file.path(FIG, "tomography", sprintf("ert_cv_vs_flux_allobs_%s.png", s)),
  sprintf("ERT CV against individual CH₄ flux measurements, %s site.", s), "Each point is one measurement; lines are per-species fits.", paste0("cv_obs_", s))
add_figure(file.path(FIG, "tomography", "decay_metric_correlations_specialists.png"), "Tree-mean flux against four wood-condition metrics in the specialist species.",
  "Lines drawn where p < 0.05. Subtitles give Pearson r, Spearman ρ and r without the tree with the highest metric value.", "decay_metrics")

print(doc, target = file.path(OUT, "Supporting_Information.docx"))
write.csv(bind_rows(items), file.path(OUT, "si_items.csv"), row.names = FALSE)
message("Wrote ", file.path(OUT, "Supporting_Information.docx"), ": ", tab_n, " tables, ", fig_n, " figures")
