# ============================================================
# 01_build_si.R
# Builds the Supporting Information document entirely from pipeline outputs:
#   outputs/manuscript/Supporting_Information.docx
#   outputs/manuscript/si_items.csv   (item number, title, source file) for cross-referencing
# Every table is formatted from a CSV written by the analysis scripts and every figure is a
# file written by them; nothing is typed by hand except captions and the decay-class key.
# Run after the full pipeline (scripts/run_pipeline.sh calls it last).
# ============================================================
suppressPackageStartupMessages({ library(officer); library(flextable); library(dplyr); library(tidyr) })
OUT <- "outputs/manuscript"; dir.create(OUT, showWarnings = FALSE, recursive = TRUE)
T_ <- "outputs/tables"; MC <- file.path(T_, "model_checks"); MN <- file.path(T_, "manuscript"); FIG <- "outputs/figures"
rd <- function(f) read.csv(f, check.names = FALSE, stringsAsFactors = FALSE)
f2 <- function(x, d = 2) formatC(x, format = "f", digits = d)
fp <- function(p) ifelse(is.na(p), "", ifelse(p < 0.001, "<0.001", formatC(p, format = "f", digits = 3)))
star <- function(p) ifelse(is.na(p), "", ifelse(p < 0.001, "***", ifelse(p < 0.01, "**", ifelse(p < 0.05, "*", ""))))
sp_full <- c(bg = "N. sylvatica", rm = "A. rubrum", hem = "T. canadensis", ro = "Q. rubra")
term_lab <- function(t) { t <- gsub("TS_Ha[12]_raw_(\\d+)h", "Temperature (\\1 h)", t); t <- gsub("bvs_wtd_cm_raw_(\\d+)h", "Water table (\\1 h)", t)
  t <- gsub("NEON_SWC_shallow_raw_(\\d+)h", "Soil water (\\1 h)", t); t <- gsub("species", "", t); t <- gsub(":", " × ", t); t }

doc <- read_docx()
items <- list(); tab_n <- 0; fig_n <- 0
# Stable keys -> SI numbers (the manuscript cites items by key; see manuscript_work/edit_manuscript.py)
TAB_KEYS <- c("decay_key", "decay_corr", "wet_comp", "slopes", "upland", "coefs", "diagnostics")
FIG_KEYS <- c("site_map", "drivers", "tree_effects", "pred_by_site", "generalists")
TXT_KEYS <- c("flux", "models", "tomo")
lab <- c(setNames(paste0("S", seq_along(TAB_KEYS)), paste0("T:", TAB_KEYS)),
         setNames(paste0("S", seq_along(FIG_KEYS)), paste0("F:", FIG_KEYS)),
         setNames(paste0("S", seq_along(TXT_KEYS)), paste0("X:", TXT_KEYS)))
fill <- function(x) { for (k in names(lab)) x <- gsub(paste0("{", k, "}"), lab[[k]], x, fixed = TRUE); x }
ft_style <- function(ft) ft %>% theme_booktabs() %>% fontsize(size = 8, part = "all") %>% font(fontname = "Arial", part = "all") %>%
  autofit() %>% fit_to_width(6.5)
add_table <- function(df, title, note, src, key) {
  tab_n <<- tab_n + 1; stopifnot(TAB_KEYS[tab_n] == key); note <- fill(note)
  doc <<- doc %>% body_add_par(sprintf("Table S%d. %s", tab_n, title), style = "Normal") %>%
    body_add_flextable(ft_style(flextable(df))) %>% body_add_par(note, style = "Normal") %>% body_add_par("", style = "Normal")
  items[[length(items) + 1]] <<- data.frame(key = paste0("T:", key), item = sprintf("Table S%d", tab_n), title = title, source = src)
}
add_figure <- function(path, title, caption, key, w = 6.5, h = NULL) {
  if (!file.exists(path)) stop("missing figure: ", path)
  fig_n <<- fig_n + 1; stopifnot(FIG_KEYS[fig_n] == key); caption <- fill(caption)
  if (is.null(h)) { dims <- dim(png::readPNG(path, native = TRUE)); h <- w * dims[1] / dims[2] }
  if (h > 8.5) { w <- w * 8.5 / h; h <- 8.5 }
  doc <<- doc %>% body_add_img(path, width = w, height = h) %>%
    body_add_par(sprintf("Figure S%d. %s %s", fig_n, title, caption), style = "Normal") %>% body_add_break()
  items[[length(items) + 1]] <<- data.frame(key = paste0("F:", key), item = sprintf("Figure S%d", fig_n), title = title, source = path)
}

doc <- doc %>% body_add_par("Supporting Information", style = "heading 1") %>%
  body_add_par("Contrasting controls on tree methane emissions in upland and wetland forests", style = "Normal") %>%
  body_add_par(sprintf("Generated by scripts/6_manuscript/01_build_si.R on %s from the pipeline outputs.", Sys.Date()), style = "Normal") %>%
  body_add_break()

# ---------------- Methods texts ----------------
md <- readLines("scripts/6_manuscript/si_methods.md", encoding = "UTF-8")
for (ln in md) {
  if (grepl("^## ", ln)) {
    k <- sub("^## (\\w+) \\|.*", "\\1", ln); ttl <- trimws(sub("^## \\w+ \\|", "", ln))
    doc <- doc %>% body_add_par(ttl, style = "heading 2")
    items[[length(items) + 1]] <- data.frame(key = paste0("X:", k), item = sub("\\..*", "", ttl), title = ttl, source = "scripts/6_manuscript/si_methods.md")
  } else if (nzchar(trimws(ln))) doc <- doc %>% body_add_par(fill(ln), style = "Normal")
}
doc <- doc %>% body_add_break()

# ---------------- Tables ----------------
# Main-text Table 1 (study trees and stand context) from 3_trees/02_stand_context.R
fx <- rd("data/final/stem_ch4_flux.csv")
st <- rd(file.path(T_, "stand_context.csv")); tot <- rd(file.path(T_, "stand_totals.csv"))
t1 <- st %>% transmute(Site = ifelse(site == "Wetland", "Wetland (BGS)", "Upland (EMS)"), Species = species, n = n_trees,
                       `DBH, mean (range), cm` = sprintf("%.1f (%.1f–%.1f)", dbh_mean_cm, dbh_min_cm, dbh_max_cm),
                       `Stand DBH quartiles, cm` = sprintf("%d / %d / %d", stand_dbh_p25_cm, stand_dbh_p50_cm, stand_dbh_p75_cm),
                       `Live basal area, % (near study trees)` = ifelse(is.na(pct_live_basal_area_near_trees), as.character(pct_live_basal_area),
                                                                     sprintf("%d (%d)", pct_live_basal_area, pct_live_basal_area_near_trees)))
write.csv(t1, file.path(OUT, "table1.csv"), row.names = FALSE, fileEncoding = "UTF-8")
write.csv(tot, file.path(OUT, "table1_totals.csv"), row.names = FALSE)

# decay classification key (merged with class counts)
key <- data.frame(Class = c("I (No decay)", "II (Incipient)", "III (Active)", "IV (Cavity)"),
  `ERT moisture anomaly` = c("No", "Yes", "Yes", "No"), `SoT structural loss > 1%` = c("No", "No", "Yes", "Yes"),
  Interpretation = c("Sound wood", "Moisture anomaly without structural loss (wetwood or early decay)",
                     "Moisture anomaly with structural loss", "Structural loss without a moisture anomaly (hollow or desiccated decay)"),
  check.names = FALSE)
cls <- rd("data/final/tomography_classes.csv") %>% filter(!is.na(decay_class)) %>% count(decay_class)
key$`Trees (n)` <- cls$n[match(sub(" .*", "", key$Class), sub(":.*", "", cls$decay_class))]
add_table(key, "Decay classification (from the companion tomography study).",
  "Moisture anomaly: species-normalized ERT PC1 above the study-set mean. Structural loss: > 1% of the SoT cross-section in non-brown (low-velocity) classes. Counts are the 57 trees with both scans.",
  "scripts/3_trees/01_tomography_classes.R", "decay_key")

# S4 wood-condition metric correlations
s4 <- rd(file.path(T_, "SI_decay_metric_correlations.csv"))
add_table(s4, "Tree-mean CH₄ flux against four wood-condition metrics, by species and site.",
  "Each cell: Pearson r (p), Spearman ρ, and the range of r when each tree is omitted in turn (LOO), for each species at each site (10 trees) and for all trees at each site (30 trees). The species-adjusted rows give the standardized coefficient β (p, likelihood-ratio test) of the metric in a mixed model of all measurements with species as a fixed effect and tree as a random effect. SoT structural loss: % of the cross-section in non-brown (low-velocity) classes; ERT mean: mean resistivity (lower = wetter); ERT CV: heterogeneity of resistivity; ERT index: first principal component of eight ERT metrics standardized within species (Thompson et al. 2026). * p < 0.05.",
  "scripts/4_analysis/07_decay_definitions.R", "decay_corr")

# S7 wetland model comparison (shared observations)
wc <- rd(file.path(MC, "wetland_model_comparison_common_rows.csv")) %>%
  transmute(Model = model, n, `Parameters (fixed)` = k_fixed, `Marginal R² (%)` = f2(100 * R2_marginal, 1), AIC = f2(AIC, 1), `ΔAIC` = f2(dAIC, 1), BIC = f2(BIC, 1), `ΔBIC` = f2(dBIC, 1))
add_table(wc, "Wetland model comparison on the observations with every driver available.",
  "All models include random intercepts for tree and sampling date. The extended model adds the predictors selected in 5_models/01_wetland_model.R (each improved the core model by likelihood-ratio test and ΔAIC < −2); the core model was retained because the extended model has a higher BIC.",
  file.path(MC, "wetland_model_comparison_common_rows.csv"), "wet_comp")

# S8 species-specific slopes: wetland core (all obs), wetland extended (shared obs), upland Model B
sl_core <- rd(file.path(MN, "species_slopes_wetland_core.csv")) %>% mutate(model = "Wetland core (all observations)")
sl_ext <- rd(file.path(MC, "wetland_species_slopes_core_vs_extended.csv")) %>% filter(model == "extended (shared rows)") %>%
  mutate(species = sp_full[species], model = "Wetland extended (shared observations)")
sl_upB <- rd(file.path(MN, "species_slopes_upland_B.csv")) %>% mutate(model = "Upland Model B")
sl <- bind_rows(sl_core, sl_ext, sl_upB) %>%
  mutate(effect = ifelse(grepl(":", term), "Temperature × water table", ifelse(grepl("^TS", term), "Temperature", "Water table")),
         cell = sprintf("%.3f ± %.3f%s", estimate, se, star(p))) %>%
  select(Model = model, Species = species, effect, cell) %>% pivot_wider(names_from = effect, values_from = cell)
add_table(sl, "Species-specific standardized effects of temperature and water table (asinh scale).",
  "Species-specific slope = reference coefficient + species interaction, ± SE; Satterthwaite t-tests. * p < 0.05; ** p < 0.01; *** p < 0.001. Upland Model B uses the wetland predictors and windows for direct comparison.",
  "species_slopes_*.csv; wetland_species_slopes_core_vs_extended.csv", "slopes")

# S9 upland models
ve <- rd(file.path(MC, "variance_explained.csv")); ab <- rd(file.path(MC, "upland_A_vs_B_common_rows.csv"))
sp_only <- ve %>% filter(model == "species only") %>% select(model_set, r2_sp = R2_marginal)
up <- ve %>% filter(model_set %in% c("upland_A", "upland_B"), model == "final") %>% left_join(sp_only, by = "model_set") %>%
  transmute(Model = ifelse(model_set == "upland_A", "A (upland drivers, 1 h)", "B (wetland drivers and windows)"), n,
            `Marginal R² (%)` = f2(100 * R2_marginal, 1), `Species only (%)` = f2(100 * r2_sp, 1),
            `AIC, all observations` = f2(AIC, 1)) %>%
  mutate(`AIC, shared observations` = f2(ab$AIC, 1), `n shared` = ab$n)
add_table(up, "Upland models.", "AIC is comparable only on the shared observations.", file.path(MC, "variance_explained.csv"), "upland")

# S10 all coefficients
co <- bind_rows(lapply(c(wetland_core = "Wetland core", upland_A = "Upland A", upland_B = "Upland B"), function(x) x) %>%
  { mapply(function(k, lab) rd(file.path(MN, paste0("coefficients_", k, ".csv"))) %>% mutate(Model = lab), names(.), ., SIMPLIFY = FALSE) }) %>%
  transmute(Model, Term = term_lab(term), Estimate = f2(estimate, 3), SE = f2(se, 3), df = f2(df, 1), t = f2(t, 2), p = fp(p))
add_table(co, "Fixed-effect coefficients of the final models (asinh scale; standardized predictors).",
  "Reference species: N. sylvatica (wetland) and A. rubrum (upland). Satterthwaite degrees of freedom.", "outputs/tables/manuscript/coefficients_*.csv", "coefs")

# S11 diagnostics: variance explained, out-of-sample, accuracy and bias
oos <- rd(file.path(MC, "out_of_sample.csv")); acc <- rd(file.path(MC, "accuracy_bias.csv")); ts <- rd(file.path(MC, "temperature_vs_season.csv"))
lab_ms <- c(wetland = "Wetland core", upland_A = "Upland A", upland_B = "Upland B")
dg <- ve %>% filter(model %in% c("species only", "final")) %>% select(model_set, model, R2_marginal) %>%
  pivot_wider(names_from = model, values_from = R2_marginal) %>%
  left_join(oos, by = "model_set") %>% left_join(acc %>% filter(prediction == "leave-one-date-out"), by = "model_set") %>%
  left_join(ts %>% select(model_set, R2_temperature_by_season, departure_LRT_p), by = "model_set") %>%
  transmute(Model = lab_ms[model_set], `R² species only` = f2(`species only`, 3), `R² final` = f2(final, 3),
            `Predictive R², leave-one-date-out (species only)` = sprintf("%.2f (%.2f)", lodo_R2_final, lodo_R2_species),
            `Predictive R², leave-one-tree-out (species only)` = sprintf("%.2f (%.2f)", loto_R2_final, loto_R2_species),
            `RMSE / bias, asinh scale` = sprintf("%.2f / %+.3f", rmse_asinh, bias_asinh),
            `MAE, nmol m⁻² s⁻¹` = f2(mae_nmol, 2),
            `Mean predicted / observed (smeared)` = sprintf("%.2f (%.2f)", ratio_mean_pred_obs, ratio_mean_smeared_obs),
            `2025 predicted from 2023–24, within range (species only)` = sprintf("%.2f (%.2f)", split2025_R2_in_range, split2025_R2_species_in_range),
            `Temperature explained by season (%)` = f2(100 * R2_temperature_by_season, 0),
            `p, temperature departure from season` = fp(departure_LRT_p))
dg <- as.data.frame(t(dg[, -1])) %>% setNames(dg$Model) %>% tibble::rownames_to_column("Diagnostic")
wpn <- rd(file.path(MC, "window_permutation.csv")) %>% group_by(model_set) %>%
  summarise(w = paste(sprintf("%s: best %d h, |r| %.2f, p %s", variable, best_window_h, max_abs_r, fp(p_perm)), collapse = "; "), .groups = "drop")
dg <- rbind(dg, c(Diagnostic = "Window screening, date-permutation test", setNames(wpn$w[match(c("wetland", "upland_A", "upland_B"), wpn$model_set)], names(dg)[-1])))
add_table(dg, "Model diagnostics.",
  "Marginal R² (Nakagawa). Out-of-sample predictions include the tree random effect (dates omitted) or fixed effects only (trees omitted). Bias = mean(predicted − observed). The back-transformed mean ratio shows the underestimate of mean flux from sinh(predicted mean); the smeared ratio applies Duan's (1983) correction. 2025 test restricted to observations within the 2023–24 predictor range. Window screening: maximum |r| over all windows (3 h–14 d) for each model driver against 500 permutations in which environmental records were reassigned among sampling dates and the search repeated.",
  "outputs/tables/model_checks/", "diagnostics")

doc <- doc %>% body_add_break()

# ---------------- Figures ----------------
add_figure(file.path(FIG, "site_map.png"), "Study sites.",
  "(a) Prospect Hill tract, Harvard Forest (inset: location in Massachusetts): shaded elevation with 10-m contours, the Black Gum Swamp outline, the study trees at the wetland (Black Gum Swamp) and upland (EMS) sites, the 40 points of the 2025 prism survey of the swamp (crosses), and the EMS (US-Ha1), hemlock (US-Ha2) and NEON (US-xHA) flux towers. (b, c) Study trees by species at the wetland (b) and upland (c) sites. Tree positions from field GPS surveys.", "site_map")
add_figure(file.path(FIG, "si_driver_timeseries.png"), "Environmental drivers over the study period.",
  "Daily means (precipitation: daily totals) from June 2023 to October 2025; vertical lines mark wetland (solid) and upland (dashed) sampling dates. Note the summer 2025 drought (falling water table and soil water content).", "drivers")
add_figure(file.path(FIG, "repeatability", "fig_tree_effects.png"), "Tree random effects.",
  "Deviation of each tree's mean asinh-transformed CH₄ flux from the mean of its species at that site (random effects from an intercept-only mixed model), with 95% intervals; red where the interval excludes zero. Trees are ordered by their effect.", "tree_effects")
add_figure(file.path(FIG, "interaction_by_site_limited_free.png"), "Model predictions by site and species.",
  "Predicted CH₄ flux across the observed temperature range at different water-table percentiles, for each species, from the wetland core model and upland Model B.", "pred_by_site")
add_figure(file.path(FIG, "tomography", "tomography_generalists.png"), "Internal wood condition and CH₄ flux in the generalist species.",
  "As Figure 5, for A. rubrum and T. canadensis at both sites; the specialists are shown in Figure 5.", "generalists")
print(doc, target = file.path(OUT, "Supporting_Information.docx"))
write.csv(bind_rows(items), file.path(OUT, "si_items.csv"), row.names = FALSE)
message("Wrote ", file.path(OUT, "Supporting_Information.docx"), ": ", tab_n, " tables, ", fig_n, " figures")
